### ISSUE TITLE
Release date?

### ISSUE THREAD

**Issue by nickspell** [ZiaMaryam/ConceptBERT#1]
Hello, as you can imagine I am really interested by your work. I was asking myself if you have any plan for releasing at a certain date/period (and if trained models will be available). Any information would be of great help. Thank you.

**Comment by maryamziaa** [comment]
Hi Nicola. Thanks for reaching out. Our developers are working on the code to make it efficient. It will be ready early 2021 hopefully. The trained models will be also available. Stay tuned! Thanks

**Comment by hackerchenzhuo** [comment]
+1

**Comment by cczka** [comment]
+10086

**Comment by iMayK** [comment]
Any updates?

**Comment by maryamziaa** [comment]
Hi Sorry this is taking longer than expected! waiting to finalize the code package.

**Comment by 156aasdfg** [comment]
Thank you very much for your outstanding work. Hope to get your open source code to learn

**Comment by xchen147** [comment]
Thanks for the great work! Very eager to learn more from the code so I would like to check in again about an updated release date.

**Comment by PamelaDDD** [comment]
Hello, first of all, thank you for your great work, and secondly, I am very interested in this work and would like to ask when your code and model will be released.

**Comment by adrielkuek** [comment]
Hi could we get an update on this? Think some of us have been waiting quite eagerly for the code implementation. Thank you so much for the amazing work!

**Comment by maryamziaa** [comment]
Hello everyone, Thank you so much for your interest. Sorry for the looong delay! I don't work in the company where I developed this code anymore. Freddy (https://github.com/flecue) and his team will release the code. I will post the link to the new Git repository once the code is released.

**Comment by maryamziaa** [comment]
Hello everyone, The code is finally released under this repository https://github.com/ThalesGroup/ConceptBERT. Sorry for a very long delay!
