### ISSUE TITLE
about the dimension of knowledge embedding from 2o2o article

### ISSUE THREAD

**Issue by alice-cool** [ZiaMaryam/ConceptBERT#3]
Dear scholar,
Could I ask about the dimension of knowledge embedding ? It contains a lot of entities embedding ?

**Comment by maryamziaa** [comment]
Hi, We used the knowledge embedding generated by this work: Commonsense Knowledge Base Completion with Structural and Semantic Context https://arxiv.org/pdf/1910.02915.pdf. In their paper they mention they used ConceptNet-100k. So there's 100k entities. For more details, please refer to their code and paper.

**Comment by maryamziaa** [comment]
I proceed to close this issue. Don't hesitate to open it again if needed.

**Comment by maryamziaa** [comment]
I proceed to close this issue. Don't hesitate to open it again if needed
