### ISSUE TITLE
about vilbert_beta data file

### ISSUE THREAD

**Issue by alice-cool** [ZiaMaryam/ConceptBERT#4]
Dear scholar,
Could you provide the google drive links for COCOdatasets. Because in china, the dropboxlink is unstable, even I bought a vpn. Sometimes it ended abruptly, but the file is too large, one is 26.3g, the other is approximately 40g.
https://www.dropbox.com/sh/09182lupkagw1ov/AACShSEVClAh6CzbhyIKxmtga?dl=0
![image](https://user-images.githubusercontent.com/16870890/115844176-292caf80-a452-11eb-9315-758e732e563f.png)

image
I also want to reproduce the results but now I didn't have the data file. Could you help me?

I am eager to get your message.

**Comment by maryamziaa** [comment]
Hi, please note that Coco dataset was published by Microsoft and you can download the dataset here https://cocodataset.org/#download. 

Unfortunately our code isn’t still published. Please check this repository later this month.

**Comment by alice-cool** [comment]
Dear scholar，
       I found in your paper，you use the fixed 36 features, I just guess if the features are from Peterson bottom up and top down provided by the github. 
https://github.com/peteanderson80/bottom-up-attention#demo
Because I found the vilbert need IMdb file that could be produced by the file from the vilbert github.
![image](https://user-images.githubusercontent.com/16870890/115867807-20e26d80-a46e-11eb-9796-8dc2b50c1c0e.png)

 I just guess but I am not sure.

**Comment by maryamziaa** [comment]
That's right. We used the bottom up attention repo to extract the features.
