### ISSUE TITLE
Some question about knowledge embedding

### ISSUE THREAD

**Issue by PamelaDDD** [ZiaMaryam/ConceptBERT#5]
Hi, scholar! Thanks for your great job! I have some questions about the usage of knowledge embedding in the paper.  How do you apply the knowledge embedding? The vocabulary file in 《Commonsense Knowledge Base Completion with Structural and Semantic Context》only contains 78334 tokens, how do you deal with the word which is out of the vocabulary file?

**Comment by maryamziaa** [comment]
Hi, Thank you for your interest in our work. This work doesn't handle out of vocabulary tokens.
